### ISSUE TITLE
T02 Lab 2 Azure Function fails

### ISSUE THREAD

**Issue by trayhumphrey** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#61] opened 2019-08-13 21:27 UTC
## Location
- Course: AZ-203
- Lab: T02 (lab 2)
- Exercise: 3
- Task: 3
- Step[s]: 13

## Description
There was a previous issue with this exercise related to DOTNET_FIRST_TIME_EXPERIENCE. This issue is not that. The file to be uploaded, function.proj, is not uploaded using the instructions shown via MS Edge browser.

## Repro steps
1. Click on View Files
2. Click on Upload
3. Choose function.proj and click Open
4. File does not upload, does not show in function app.

## Fix
I fixed this simply by adding a file called function.proj from View Files and then pasting in the contents of the local function.proj file. After that, the function worked. Not sure why Upload didn't work.

**Comment by seesharprun** [comment] 2019-08-13 21:40
I just validated that this issue occurs in Microsoft Edge but not Chrome or Edge Dev.

This impacts both labs 2 & 4. I will need to test that adding the function.proj manually to both labs does not create a side effect.

On the surface, it doesn't seem it will.

**Comment by trayhumphrey** [comment] 2019-08-13 22:10
Thanks for the quick test, @seesharprun. Chrome is a great workaround for now as many students use it anyway.

**Comment by seesharprun** [comment] 2019-08-13 22:18
At first, I thought we would just push the lab environment to Dev Edge (which is based on Chromium) to resolve the issue.

On deeper thought, I realized that I would rather have lab instructions that work on all three browsers. I’ll get a fix going this week.

**Comment by trayhumphrey** [comment] 2019-08-13 22:23
Just for my $0.02, thank you. I have students who will sometimes repeat labs after class is over. The less pre-production software, the fewer overall issues over time. 

Looking forward to Edge on Chromium, btw... Best of both worlds, I hope.  ;)

**Comment by seesharprun** [comment] 2019-08-13 22:33
Edge Dev is what caused this bug. It’s been my daily browser for a while now and I never noticed the Edge bug in the lab instructions.

Chromium is pretty mature so it’s not as far off as you think.

I opened a separate issue #62 to discuss potential lab VM updates.

**Comment by vitaly-livshits** [comment] 2019-08-14 01:21
My students ran into this issue this afternoon, just before this GitHub issue was opened. 

They were able to work around it by adding the file and then copying & pasting the contents from the lab instructions.

@seesharprun, it seems that the root cause of this issue is an Azure Portal bug. If so, would it make sense to raise it to the Azure team for resolution?

**Comment by trayhumphrey** [comment] 2019-08-14 01:35
Yes, @vitaly-livshits, see my FIX listed in the original issue. I found the same work around. And this has been confirmed as a bug in MS Edge, not the Azure Portal. The upload works fine in Chrome.

**Comment by vitaly-livshits** [comment] 2019-08-14 01:53
@trayhumphrey Thanks. My impression based on this thread was that it was an interaction of Azure Portal and Edge (i.e. website issue around browser compatibility), rather than a bug in Edge per se.

**Comment by seesharprun** [comment] 2019-08-15 13:52
I will have this fixed by the end of this week. I have the updated instructions now but they are undergoing testing.

**Comment by trayhumphrey** [comment] 2019-08-17 12:04
Thanks, Sydney. And thank you for being so responsive about issues on your repos. I know it is extra work and not your "real job", but all MCTs benefit from your diligence. Students have a much more positive experience when labs work. Go figure! Unfortunately, I have run across other MOC repo managers who leave a bit to be desired, so thanks again!

**Comment by seesharprun** [comment] 2019-08-20 22:55
> I'm updating each of the open issues this week to let you know that there was a small delay in the latest round of updates. They should be ready about one week later than originally anticipated.

**Comment by seesharprun** [comment] 2019-08-22 12:46
A couple of updates here:

- **Lab 2**
    - Updated lab to create the **function.proj** file manually
    - While the ``DOTNET_FIRST_TIME_EXPERIENCE`` variable is not necessary, I left the steps in so attendees can see how to set .NET Core variables
- **Lab 4**
    - Updated lab to create the **function.proj** file manually
    - Updated the [Microsoft.Azure.Storage.Blob](https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/11.0.0) NuGet package to Version 11.0.0
        - The namespaces moving forward have been changed from ``Microsoft.WindowsAzure.Storage.*`` to ``Microsoft.Azure.Storage.*``

These changes can be seen in [Version 20190822.02](https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/releases/tag/v20190822.02).

**Closed by seesharprun** 2019-08-22 12:46 UTC
